;;; init.el --- Emacs Init File -*- lexical-binding: t; -*-

;;; Imports & Redirects
(add-to-list 'load-path "~/.emacs.d/lisp") 			; Add extra configuration directory to load-path 
(setq custom-file "~/.emacs.d/custom.el")      		; Place all configs generated by `customize` outside of init.el

;;; History
(setq history-length 25)         					; Maximum minibuffer history length
(recentf-mode 1)                 					; Remember recently edited file
(savehist-mode 1)                					; Remember minibuffer history
(save-place-mode 1)              					; Remember last cursor position
(global-auto-revert-mode 1)      					; Refresh buffer on external file change

;;; Indentation
(setq-default indent-tabs-mode nil)					; Indent command only uses spaces
(setq-default tab-width 4)						    ; Set default tab width (4 spaces)
(setq-default tab-always-indent nil)                ; Only indent line when at BOL or in a line's indentation.

;;; UI - Appearance
(load-theme 'modus-vivendi t)    					; Load ui theme
(global-display-line-numbers-mode 1)                ; Display line numbers
(global-visual-line-mode t)                         ; Enable word wrap

;;; UI - Hidden Elements
(menu-bar-mode -1)               					; Disable menu bar
(tool-bar-mode -1)               					; Disable tool bar
(scroll-bar-mode -1)             					; Disable scroll bar
(fringe-mode 0)                  					; Disable fringes
(setq-default use-dialog-box nil)        			; Don't show pop-up UI dialogs when prompting
(setq-default frame-inhibit-implied-resize t)
(setq-default inhibit-startup-screen t)
(setq-default inhibit-startup-message t)
(setq-default inhibit-scratch-message t)


;;; Frame
;; Set initial frame size to fullheight
(setq frame-resize-pixelwise t)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
;; Set frame title to file name
(setq frame-title-format
      '(buffer-file-name (:eval (abbreviate-file-name buffer-file-name))
			 (dired-directory dired-directory "%b")))
;; Focus new frames
(defun rr/focus-new-client-frame ()
  (select-frame-set-input-focus (selected-frame)))
(add-hook 'server-after-make-frame-hook #'rr/focus-new-client-frame)

;;; Font
;; Helper function to determine if a font exists on the system
(defun font-exists-p (font) (if (null (x-list-fonts font)) nil t))
;; Font defaults
(set-face-attribute 'default nil :family "Lilex" :height 120 :weight 'medium)
(set-face-attribute 'fixed-pitch nil :family "Lilex" :height 1.0 :weight 'medium)
(set-face-attribute 'variable-pitch nil :family "Lilex" :height 120 :weight 'medium)
(add-to-list 'default-frame-alist '(font . "Lilex"))
;; Line Spacing
;(setq-default line-spacing 0.12)

;; Packages
(require 'packages)
