;;; init.el --- Emacs Init File -*- lexical-binding: t; -*-

;;; General ;;;
(setq-default make-backup-files nil)    ; Disable backup files for each buffer (file_name.ext~)
(setq load-prefer-newer t)              ; Always load newest byte-code

;;; Imports & Redirects ;;;
(add-to-list 'load-path "~/.emacs.d/lisp") 	 ; Add extra configuration directory to load-path 
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")   ; Add theme directory to custom theme load-path
(setq custom-file "~/.emacs.d/custom.el") ; Place all configs generated by `customize` outside of init.el

;;; History ;;;
(setq history-length 25)         					    ; Maximum minibuffer history length
(recentf-mode 1)                 					    ; Remember recently edited file
(savehist-mode 1)                					    ; Remember minibuffer history
(save-place-mode 1)              					    ; Remember last cursor position
(global-auto-revert-mode 1)      					    ; Refresh buffer on external file change

;;; Indentation ;;;
(setq-default indent-tabs-mode nil)					    ; Indent command only uses spaces
(setq-default tab-width 4)						        ; Set default tab width (4 spaces)
(setq-default tab-always-indent nil)                    ; Only indent line when at BOL or in a line's indentation.

;;; UI - Appearance ;;;
(global-visual-line-mode t)                             ; Enable word wrap
(add-hook 'prog-mode-hook #'display-line-numbers-mode)  ; Enable line-numbers in programming mode

;;; UI - Hidden Elements ;;;
(menu-bar-mode   -1)               					    ; Disable menu bar
(tool-bar-mode   -1)               					    ; Disable tool bar
(scroll-bar-mode -1)             					    ; Disable scroll bar
(fringe-mode      0)              					    ; Disable fringes
(setq-default use-dialog-box nil)        			    ; Don't show pop-up UI dialogs when prompting
(setq-default frame-inhibit-implied-resize t)
(setq-default inhibit-startup-screen t)
(setq-default inhibit-startup-message t)
(setq-default inhibit-scratch-message t)

;;; Frame ;;;
;; Set initial frame size to fullheight
(setq frame-resize-pixelwise t)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
;; Set frame title to file name
(setq frame-title-format
      '(buffer-file-name (:eval (abbreviate-file-name buffer-file-name))
			 (dired-directory dired-directory "%b")))
;; Focus new frames
(defun rr/focus-new-client-frame ()
  (select-frame-set-input-focus (selected-frame)))
(add-hook 'server-after-make-frame-hook #'rr/focus-new-client-frame)

;;; Font ;;;
(set-face-attribute 'default nil :family "Lilex" :height 120 :weight 'regular)
(set-face-attribute 'fixed-pitch nil :family "Lilex" :height 1.0 :weight 'regular)
(set-face-attribute 'variable-pitch nil :family "Lilex" :height 120 :weight 'regular)
(add-to-list 'default-frame-alist '(font . "Lilex"))
;(setq-default line-spacing 0.12)

;;; Theme ;;;
(load-theme 'sunburst t)

;;; Packages ;;;
(require 'packages)
